* 

** 4:00 p.m., Thursday, 14 July 2022

We've been having our Zooms for 2+ years and they've been a support in the
challenges of life and a wonderful connection with dear friends. And I'd like to
create something new!

The new idea is a 1-hour Zoom with a structure somewhat like the Zegg Forum,
which is to say that 1 person shares at a time and there are 1 or two
facilitators who help keep the person sharing present in their immediate
experience, help to draw them out and manage time. I want to open it up to
anyone (1) who we have a connection with (2) who has some background in
authentic communication, e.g. from HAI, Zegg/NFNC, MPK, NVC, et al. And (3) who
are serious about doing the work to have a great life and empower their
communities.

As a symbol of this destruction of the old and creation of the new, and in an
attempt to make it more available to those who have more conventional weekly
time commitments, let's hold these new Zoom Meetings every other week on
Wednesdays, from 5pm - 6pm. The first of these new meetings will therefore be
Wednesday the 27th of July.
